# Generated by Django 3.0.3 on 2020-03-16 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='discount_price',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
